# Use the official Nginx image as a base image
FROM nginx:latest

# Copy the build files from the local machine to the container
COPY ./build /usr/share/nginx/html

# Expose port 80 for Nginx
EXPOSE 80

# Start Nginx in the foreground
CMD ["nginx", "-g", "daemon off;"]
