version: '3.8'

services:
  laravel:
    build:
      context: ./laravel
      dockerfile: Dockerfile
    working_dir: /var/www
    container_name: laravel
    volumes:
      - ./laravel:/var/www
    networks:
      - laravel-network

  queue:
    build:
      context: ./laravel
      dockerfile: Dockerfile
    container_name: queue
    command: 'php artisan queue:work'
    depends_on:
      - db
    networks:
      - laravel-network

  db:
    platform: linux/x86_64
    image: mysql:8.0
    container_name: database
    environment:
      MYSQL_DATABASE: team_challenge
      MYSQL_USER: master
      MYSQL_ROOT: "root"
      MYSQL_PASSWORD: 123
      MYSQL_ROOT_PASSWORD: 123
    volumes:
      - db:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - laravel-network

  # nginx:
  #   container_name: nginx
  #   image: nginx:latest
  #   build:
  #     context: ./nginx
  #     dockerfile: Dockerfile
  #   volumes:
  #     # Mount SSL certificate for HTTPS
  #     - ./nginx/ssl:/etc/nginx/ssl:ro
  #     - ./nginx/conf.d:/etc/nginx/conf.d:ro
  #     # - ./react/build:/etc/nginx/html
  #   tty: true
  #   depends_on:
  #     - laravel
  #     - react-prod
  #   networks:
  #     - laravel-network

  react-prod:  # Production service
    container_name: react-prod
    build:
      context: ./react
      dockerfile: Dockerfile.prod
    # volumes:
    #   - shared_data:/react_build
    # ports:
    #   - '80:80'
    networks:
      - laravel-network

networks:
  laravel-network:
    driver: bridge

volumes:
  db:
    driver: local
