version: '3.8'

services:
  laravel:
    build:
      context: ./laravel
      dockerfile: Dockerfile
    working_dir: /var/www
    volumes:
      - ./laravel:/var/www
    networks:
      - laravel-network

  queue:
    build:
      context: ./laravel
      dockerfile: Dockerfile
    command: 'php artisan queue:work'
    depends_on:
      - db
    networks:
      - laravel-network

  db:
    platform: linux/x86_64
    image: mysql:8.0
    container_name: Database
    environment:
      MYSQL_DATABASE: team_challenge
      MYSQL_USER: master
      MYSQL_ROOT: "root"
      MYSQL_PASSWORD: 123
      MYSQL_ROOT_PASSWORD: 123
    volumes:
      - db:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - laravel-network

  nginx:
    image: nginx:latest
    ports:
      # Use 443 for HTTPS
      # - '443:443'
      # Use 80 for HTTP
      - '80:80'
    volumes:
      # Mount SSL certificate for HTTPS
      # - ./nginx/ssl:/etc/nginx/ssl:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./react/build:/etc/nginx/html
    depends_on:
      - laravel
    networks:
      - laravel-network

networks:
  laravel-network:
    driver: bridge

volumes:
  db:
    driver: local
