version: '3.8'

services:
  laravel:
    build:
      context: ./laravel
      dockerfile: Dockerfile
    working_dir: /var/www
    container_name: laravel
    volumes:
      - ./laravel:/var/www
    networks:
      - laravel-network

  queue:
    build:
      context: ./laravel
      dockerfile: Dockerfile
    container_name: queue
    command: 'php artisan queue:work'
    depends_on:
      - db
    networks:
      - laravel-network

  db:
    platform: linux/x86_64
    image: mysql:8.0
    container_name: database
    environment:
      MYSQL_DATABASE: team_challenge
      MYSQL_USER: master
      MYSQL_ROOT: "root"
      MYSQL_PASSWORD: 123
      MYSQL_ROOT_PASSWORD: 123
    volumes:
      - db:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - laravel-network

  nginx:
    container_name: nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    volumes:
      # Mount SSL certificate for HTTPS
      # - ./nginx/ssl:/etc/nginx/ssl:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./react/build:/etc/nginx/html
    # command: sh -c "mkdir -p /etc/nginx/ssl && \
    #          openssl genrsa -des3 -passout pass:x -out /etc/nginx/ssl/server.pass.key 2048 && \
    #          openssl rsa -passin pass:x -in /etc/nginx/ssl/server.pass.key -out /etc/nginx/ssl/server.key && \
    #          rm /etc/nginx/ssl/server.pass.key && \
    #          openssl req -new -key /etc/nginx/ssl/server.key -out /etc/nginx/ssl/server.csr -subj '/C=UK/ST=Warwickshire/L=Leamington/O=OrgName/OU=IT Department/CN=172.20.0.1' && \
    #          openssl x509 -req -days 365 -in /etc/nginx/ssl/server.csr -signkey /etc/nginx/ssl/server.key -out /etc/nginx/ssl/server.crt"
    depends_on:
      - laravel
    networks:
      - laravel-network

networks:
  laravel-network:
    driver: bridge

volumes:
  db:
    driver: local
