version: '3.8'

services:
  laravel:
    build:
      context: ./laravel
      dockerfile: Dockerfile
    container_name: laravel
    networks:
      - laravel-network

  queue:
    build:
      context: ./laravel
      dockerfile: Dockerfile
    container_name: queue
    command: 'php artisan queue:work'
    depends_on:
      - db
    networks:
      - laravel-network

  db:
    platform: linux/x86_64
    image: mysql:8.0
    container_name: database
    environment:
      MYSQL_DATABASE: team_challenge
      MYSQL_USER: master
      MYSQL_ROOT: "root"
      MYSQL_PASSWORD: 123
      MYSQL_ROOT_PASSWORD: 123
    ports:
      - 3306:3306
    networks:
      - laravel-network

  nginx-react:
    container_name: nginx-react
    build:
      context: ./react
      dockerfile: Dockerfile.prod
    ports:
      - '1443:443'
    networks:
      - laravel-network

networks:
  laravel-network:
    driver: bridge

volumes:
  db:
    driver: local
