# Tutorial
# https://blog.vishnuprasaath.dev/dockerize-react-app-for-dev-and-prod

version: "3.8"

services:
  app:
    container_name: app-dev-c
    image: app-dev-i
    build:
      context: .react
      dockerfile: Dockerfile.dev
    volumes:
      - ./src:/app/src
    ports:
      - "3000:3000"
