FROM node:14-alpine AS development
ENV NODE_ENV development

# Cache and Install dependencies
COPY package.json .
COPY package-lock.json .

#RUN yarn install
RUN npm i --frozen-lockfile

# Copy app files
COPY . .

# Expose port
EXPOSE 3000

# Start the app
CMD [ "yarn", "start-https" ]
